#!/bin/bash
<<doc
Name:Devika Ashok
Date:
Description:Script for arithmetic calculator using command line argument
Sample Input:
Sample Output:
doc
if [ $# -ne 0 ]           #length of cla not equal to zero
then
    if [ $# -eq 3 ]      #length of cla should be equal to 3
    then
        case $2 in          #second cla gives the arithmetic operator

            +)
                add=`echo $1 + $3|bc`    #addition done
                echo "$1 $2 $3 = $add"
                ;;
            -)
                sub=`echo $1 - $3|bc`      #substraction done
                echo "$1 $2 $3 = $sub"
                ;;
            x)
                mul=`echo $1*$3|bc`         #multiplication done
                echo "$1 $2 $3 = $mul"
                ;;
            /)

                div=`echo "scale=2;$1 / $3"|bc`  #division done
                echo "$1 $2 $3 = $div"
                ;;
            *)
                echo "Please pass valid operator"
                ;;
        esac
    else
        echo "Error:Please enter 3 arguments."
        echo "Usage:./arithmatic_calc.sh 2.3 + 6.7"
    fi
else
    echo "Error:Please pass the argument through command line."
    echo "Usage:./arithmatic_calc.sh 2.3 + 6.7"
fi
